In [1]:
%load_ext autoreload
# %autoreload 2

In [2]:
%autoreload 2
from src import matriz_aumentada, gauss_jordan

A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
b = [1, -2, 3, 4]

Ab = matriz_aumentada(A, b) # type: ignore
gauss_jordan(Ab)

[02-02 11:29:29][INFO][pc] 2026-02-02 11:29:29.576090


[02-02 11:29:30][INFO][pc] 2026-02-02 11:29:30.263436
[02-02 11:29:30][INFO][pc] 2026-02-02 11:29:30.278520
[02-02 11:29:30][INFO][pc] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0. -1. -3. -6.  0.]]
[02-02 11:29:30][INFO][pc] 
[[ 1.  0.  3.  6.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0. -3. -7. -4.]]
[02-02 11:29:30][INFO][pc] 
[[ 1.  0.  0. -3.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0.  0.  2. -4.]]
[02-02 11:29:30][INFO][pc] 
[[ 1.  0.  0.  0.  3.]
 [ 0.  1.  0.  0. -6.]
 [ 0.  0. -1.  0. -6.]
 [ 0.  0.  0.  2. -4.]]


array([ 3., -6.,  6., -2.])

# Resolver

In [3]:
import logging
from sys import stdout
from datetime import datetime
import os

logging.basicConfig(
    level=logging.INFO,
    format=f"[%(asctime)s][%(levelname)s][{os.environ.get('USERNAME')}] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[02-02 11:29:34][INFO][pc] 2026-02-02 11:29:34.897277


In [44]:
import numpy as np

def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante el método de Gauss-Jordan.

    ## Parameters

    ``A``: matriz aumentada del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(n+1), donde n es el número de incógnitas.

    ## Return

    ``solucion``: vector con la solución del sistema de ecuaciones lineales.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)  # convertir en float, porque si no, convierte en enteros
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            logging.info(f"\n{A}")
            raise ValueError("No existe solución única.")

        if p != i:
            logging.info(f"Intercambiando filas {i} y {p}.")
            # swap rows
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        for j in range(n):
            if i == j:
                continue
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]
        A[i, :] = A[i, :] / A[i, i]

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    # # --- Sustitución hacia atrás
    # solucion = np.zeros(n)
    # for i in range(n):
    #     solucion[i] = A[i, n] / A[i, i]

    # return solucion

## Ejemplos
* Ejemplo 1

In [46]:
# La matriz A =
A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
# tiene como inversa
# A_inv =[[ 0.5, -0.5, -1.5,  1.5],
#        [-0.5,  1.5, -1.5,  0.5],
#        [-1.5, -1.5,  3.5, -1.5],
#        [ 1.5,  0.5, -1.5,  0.5]]
#inv_matrix(A)

* Ejemplo 2

In [48]:
# La matriz A =
A = [
    [4, 4, 5, 1],
    [3, 4, 2, 2],
    [2, 1, 4, 1],
    [3, 2, 5, 4],
]
# tiene como inversa
# A_inv =[[-34.,  31.,  52., -20.],
#         [ 19., -17., -29.,  11.],
#         [ 12., -11., -18.,   7.],
#         [  1.,  -1.,  -2.,   1.]]
#inv_matrix(A)

## Ejercicios

* Ejercicio 1

In [51]:
A = [[2, -3], [-1, 1]]

In [52]:
print(A)
gauss_jordan(A)

[[2, -3], [-1, 1]]
[02-02 11:50:46][INFO][pc] Intercambiando filas 0 y 1.
[02-02 11:50:46][INFO][pc] 
[[ 1. -1.]
 [ 0. -1.]]
[02-02 11:50:46][INFO][pc] 
[[ 1.  0.]
 [-0.  1.]]


- Matriz aumentada

In [19]:
n = len(A)
m_aug = np.hstack((A, np.eye(n)))
m_aug

array([[ 2., -3.,  1.,  0.],
       [-1.,  1.,  0.,  1.]])

In [27]:
inv_matrix = gauss_jordan(m_aug)
inv_matrix

[02-02 11:43:22][INFO][pc] 
[[ 1.  0. -1. -3.]
 [ 0.  1. -1. -2.]]
[02-02 11:43:22][INFO][pc] 
[[ 1.  0. -1. -3.]
 [ 0.  1. -1. -2.]]


* Comprobación 

In [25]:
np.linalg.inv(A)

array([[-1., -3.],
       [-1., -2.]])

* Ejercicio 2

In [53]:
A = [
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
]

In [54]:
print(A)
gauss_jordan(A)

[[4, 0, 0, 5], [1, 0, 4, 0], [3, 4, 1, 3], [1, 3, 3, 0]]
[02-02 11:50:55][INFO][pc] Intercambiando filas 0 y 1.
[02-02 11:50:55][INFO][pc] 
[[  1.   0.   4.   0.]
 [  0.   0. -16.   5.]
 [  0.   4. -11.   3.]
 [  0.   3.  -1.   0.]]
[02-02 11:50:55][INFO][pc] Intercambiando filas 1 y 3.
[02-02 11:50:55][INFO][pc] 
[[  1.           0.           4.           0.        ]
 [  0.           1.          -0.33333333   0.        ]
 [  0.           0.          -9.66666667   3.        ]
 [  0.           0.         -16.           5.        ]]
[02-02 11:50:55][INFO][pc] 
[[ 1.          0.          0.          1.24137931]
 [ 0.          1.          0.         -0.10344828]
 [-0.         -0.          1.         -0.31034483]
 [ 0.          0.          0.          0.03448276]]
[02-02 11:50:55][INFO][pc] 
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1.  0.]
 [ 0.  0.  0.  1.]]


* Matriz aumentada

In [55]:
n = len(A)
m_aug = np.hstack((A, np.eye(n)))
m_aug

array([[4., 0., 0., 5., 1., 0., 0., 0.],
       [1., 0., 4., 0., 0., 1., 0., 0.],
       [3., 4., 1., 3., 0., 0., 1., 0.],
       [1., 3., 3., 0., 0., 0., 0., 1.]])

In [56]:
inv_matrix = gauss_jordan(m_aug)
inv_matrix

[02-02 11:51:13][INFO][pc] Intercambiando filas 0 y 1.
[02-02 11:51:13][INFO][pc] 
[[  1.   0.   4.   0.   0.   1.   0.   0.]
 [  0.   0. -16.   5.   1.  -4.   0.   0.]
 [  0.   4. -11.   3.   0.  -3.   1.   0.]
 [  0.   3.  -1.   0.   0.  -1.   0.   1.]]
[02-02 11:51:13][INFO][pc] Intercambiando filas 1 y 3.
[02-02 11:51:13][INFO][pc] 
[[  1.           0.           4.           0.           0.
    1.           0.           0.        ]
 [  0.           1.          -0.33333333   0.           0.
   -0.33333333   0.           0.33333333]
 [  0.           0.          -9.66666667   3.           0.
   -1.66666667   1.          -1.33333333]
 [  0.           0.         -16.           5.           1.
   -4.           0.           0.        ]]
[02-02 11:51:13][INFO][pc] 
[[ 1.          0.          0.          1.24137931  0.          0.31034483
   0.4137931  -0.55172414]
 [ 0.          1.          0.         -0.10344828  0.         -0.27586207
  -0.03448276  0.37931034]
 [-0.         -0.         

* Comprobación

In [34]:
np.linalg.inv(A)

array([[-36.,  45.,  60., -80.],
       [  3.,  -4.,  -5.,   7.],
       [  9., -11., -15.,  20.],
       [ 29., -36., -48.,  64.]])

* Ejercicio 3

In [36]:
A = [
    [0, 0, 0, 0, 0, 0, 1, -1],
    [0, 1, -1, 1, 0, -1, 0, 1],
    [-1, -1, 0, 0, 2, 1, 0, 0],
    [-1, -1, -1, 1, 2, 0, 0, 1],
    [-1, 1, 1, 0, -1, -1, 0, 2],
    [0, 1, 0, 0, -1, -1, 0, 0],
    [1, -1, -1, 1, 2, 1, 0, 2],
    [2, 0, 0, 0, 0, 1, 2, 0],
]
#inv_matrix(A)

In [37]:
print(A)
gauss_jordan(A)

[[0, 0, 0, 0, 0, 0, 1, -1], [0, 1, -1, 1, 0, -1, 0, 1], [-1, -1, 0, 0, 2, 1, 0, 0], [-1, -1, -1, 1, 2, 0, 0, 1], [-1, 1, 1, 0, -1, -1, 0, 2], [0, 1, 0, 0, -1, -1, 0, 0], [1, -1, -1, 1, 2, 1, 0, 2], [2, 0, 0, 0, 0, 1, 2, 0]]
[02-02 11:49:10][INFO][pc] Intercambiando filas 0 y 2.
[02-02 11:49:10][INFO][pc] 
[[ 1.  1. -0. -0. -2. -1. -0. -0.]
 [ 0.  1. -1.  1.  0. -1.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.]
 [ 0.  2.  1.  0. -3. -2.  0.  2.]
 [ 0.  1.  0.  0. -1. -1.  0.  0.]
 [ 0. -2. -1.  1.  4.  2.  0.  2.]
 [ 0. -2.  0.  0.  4.  3.  2.  0.]]
[02-02 11:49:10][INFO][pc] 
[[ 1.  0.  1. -1. -2.  0. -0. -1.]
 [ 0.  1. -1.  1.  0. -1.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.]
 [ 0.  0.  3. -2. -3.  0.  0.  0.]
 [ 0.  0.  1. -1. -1.  0.  0. -1.]
 [ 0.  0. -3.  3.  4.  0.  0.  4.]
 [ 0.  0. -2.  2.  4.  1.  2.  2.]]
[02-02 11:49:10][INFO][pc] Intercambiando filas 2 y 3.
[02-02 11:49:10][INFO][pc] 
[[ 1.  0.  0.  0. -2

In [38]:
n = len(A)
m_aug = np.hstack((A, np.eye(n)))
m_aug

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  1., -1.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  1., -1.,  1.,  0., -1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [-1., -1.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.],
       [-1., -1., -1.,  1.,  2.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.],
       [-1.,  1.,  1.,  0., -1., -1.,  0.,  2.,  0.,  0.,  0.,  0.,  1.,
         0.,  0.,  0.],
       [ 0.,  1.,  0.,  0., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.],
       [ 1., -1., -1.,  1.,  2.,  1.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  0.],
       [ 2.,  0.,  0.,  0.,  0.,  1.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.]])

In [39]:
inv_matrix = gauss_jordan(m_aug)
inv_matrix

[02-02 11:49:19][INFO][pc] Intercambiando filas 0 y 2.
[02-02 11:49:19][INFO][pc] 
[[ 1.  1. -0. -0. -2. -1. -0. -0. -0. -0. -1. -0. -0. -0. -0. -0.]
 [ 0.  1. -1.  1.  0. -1.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.  0.  0. -1.  1.  0.  0.  0.  0.]
 [ 0.  2.  1.  0. -3. -2.  0.  2.  0.  0. -1.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0. -1. -1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0. -2. -1.  1.  4.  2.  0.  2.  0.  0.  1.  0.  0.  0.  1.  0.]
 [ 0. -2.  0.  0.  4.  3.  2.  0.  0.  0.  2.  0.  0.  0.  0.  1.]]
[02-02 11:49:19][INFO][pc] 
[[ 1.  0.  1. -1. -2.  0. -0. -1. -0. -1. -1. -0. -0. -0. -0. -0.]
 [ 0.  1. -1.  1.  0. -1.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.  0.  0. -1.  1.  0.  0.  0.  0.]
 [ 0.  0.  3. -2. -3.  0.  0.  0.  0. -2. -1.  0.  1.  0.  0.  0.]
 [ 0.  0.  1. -1.

* Ejercicio 4

In [40]:
A = [
    [1, 0, 0, 0, -1, 0, 0, -1, 1, -1],
    [1, 1, 0, -1, -1, 1, 0, 0, 1, -1],
    [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0],
    [0, 0, -1, 0, -1, -1, 1, 0, 1, 0],
    [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1],
    [1, 0, 0, 1, -1, -1, -1, 1, -1, 0],
    [1, 1, 1, 0, 1, 0, -1, -1, -1, 1],
    [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, -1, -1, 0, 0],
    [0, 0, -1, -1, -1, 0, 1, 1, 1, -1],
]
#inv_matrix(A)

In [41]:
print(A)
gauss_jordan(A)

[[1, 0, 0, 0, -1, 0, 0, -1, 1, -1], [1, 1, 0, -1, -1, 1, 0, 0, 1, -1], [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0], [0, 0, -1, 0, -1, -1, 1, 0, 1, 0], [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1], [1, 0, 0, 1, -1, -1, -1, 1, -1, 0], [1, 1, 1, 0, 1, 0, -1, -1, -1, 1], [1, 1, 1, 1, 0, 0, 1, 1, 0, 0], [1, 1, 1, 1, 1, 0, -1, -1, 0, 0], [0, 0, -1, -1, -1, 0, 1, 1, 1, -1]]
[02-02 11:49:32][INFO][pc] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.]
 [ 0.  1.  0. -1.  0.  1.  0.  1.  0.  0.]
 [ 0.  0. -1.  0. -1.  0. -1.  0.  1. -1.]
 [ 0.  0. -1.  0. -1. -1.  1.  0.  1.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  1. -2.]
 [ 0.  0.  0.  1.  0. -1. -1.  2. -2.  1.]
 [ 0.  1.  1.  0.  2.  0. -1.  0. -2.  2.]
 [ 0.  1.  1.  1.  1.  0.  1.  2. -1.  1.]
 [ 0.  1.  1.  1.  2.  0. -1.  0. -1.  1.]
 [ 0.  0. -1. -1. -1.  0.  1.  1.  1. -1.]]
[02-02 11:49:32][INFO][pc] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.]
 [ 0.  1.  0. -1.  0.  1.  0.  1.  0.  0.]
 [ 0.  0. -1.  0. -1.  0. -1.  0.  1. -1.]
 [ 0.  0. -1.  0. -1. -1.  1.  0.  

In [42]:
n = len(A)
m_aug = np.hstack((A, np.eye(n)))
m_aug

array([[ 1.,  0.,  0.,  0., -1.,  0.,  0., -1.,  1., -1.,  1.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0., -1., -1.,  1.,  0.,  0.,  1., -1.,  0.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0., -1.,  0.,  0.,  0., -1.,  1.,  0.,  0.,  0.,  0.,  1.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0., -1., -1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  0.,  0., -1.,  1.,  1.,  1.,  1.,  0., -1.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  1., -1., -1., -1.,  1., -1.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  1.,  0., -1., -1., -1.,  1.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  0., -1., -1.,  0.,  0.,  0.,  

In [43]:
inv_matrix = gauss_jordan(m_aug)
inv_matrix

[02-02 11:49:41][INFO][pc] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  1.  0. -1.  0.  1.  0.  1.  0.  0. -1.  1.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0. -1.  0. -1.  0. -1.  0.  1. -1.  1.  0.  1.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0. -1.  0. -1. -1.  1.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  1. -2.  1.  0.  0.  0.  1.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  1.  0. -1. -1.  2. -2.  1. -1.  0.  0.  0.  0.  1.  0.  0.
   0.  0.]
 [ 0.  1.  1.  0.  2.  0. -1.  0. -2.  2. -1.  0.  0.  0.  0.  0.  1.  0.
   0.  0.]
 [ 0.  1.  1.  1.  1.  0.  1.  2. -1.  1. -1.  0.  0.  0.  0.  0.  0.  1.
   0.  0.]
 [ 0.  1.  1.  1.  2.  0. -1.  0. -1.  1. -1.  0.  0.  0.  0.  0.  0.  0.
   1.  0.]
 [ 0.  0. -1. -1. -1.  0.  1.  1.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  1.]]
[02-02 11:49:41][INFO][pc] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  1